#!/usr/bin/env node

const { Command } = require('commander')
const program = new Command()

program.command('product-node-types', 'export product node types')
	.requiredOption('-t, --token <api token>', 'api token to use for request')
	.requiredOption('-e, --endpoint <api endpoint>', 'api token to use for request')
	.argument('<types>', 'JSON string representing types to import from exported file')
	.action(async (types, options) => {
		const { importTypes } = await import("./graph/import.mjs");

		await importTypes(JSON.parse(types), options.token, options.endpoint)
	})

program.parse()