#!/usr/bin/env node

const { Command } = require('commander')
const program = new Command()

program
	.command('auth', 'get and store a new token from the API using configured credentials')
	.argument('<name>', 'the alias you want to use when referencing this tenant in other commands')
	.action(async (name) => {
		const { fetchNewToken, saveToken } = await import("./tenant/config.mjs");
		const token = await fetchNewToken(name)
		await saveToken(name, token)
		console.log(`new token \`${token}\` stored and ready for use`)
	})

program.parse()