#!/usr/bin/env node

const { Command } = require('commander')
const program = new Command()

program
	.command('create', 'configure a new tenant')
	.command('info', 'show stored information about tenant')
	.command('auth', 'get and store a new token from the API using configured credentials')

program.parse()