#!/usr/bin/env node

const { Command } = require('commander')

const program = new Command()

program.command('export', 'export bulk data from various domains')
program.command('import', 'import bulk data to various domains')
program.command('copy', 'shortcut to import and export between tenants')
program.command('create-tenant', 'create a new tenant')

program.parse()
