name: Publish

on:
  push:
    tags:        
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --ignore-scripts

      - name: Publish package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
